id: PE1E7933F
initial_creation_type: ocr
source_metadata:
  volumes:
    6c66b8042fc34b8ba7e6f055bd969890:
      base_file: v060.txt
      image_group_id: I1PD95905
      title: དབུ་མ་ལ་འཇུག་པའི་བཤད་པ།
      total_pages: 1913
      volume_number: 60
